
services:
  - type: static
    name: hrms
    env: node
    buildCommand: npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html